import { Inter } from 'next/font/google'
import './globals.css'
import GlobalState from '@/context'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Terra Crafted',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <GlobalState>
          <Navbar />
          <main className='flex  flex-col mt-[80px]'>{children}</main>
        </GlobalState>
      </body>
    </html>
  )
}
